### PR TITLE
Implement directory slugs in URL 

### LINKED ISSUE #3: Special characters in folder name break the folder
**Summary**  
Some URL special characters (`&`, `/`, etc.) are allowed in folder names, and render the folder inaccessible. 

**Environment**  
Version: [Release v0.1](https://github.com/kanishka-linux/reminiscence/releases/tag/v0.1)
Python: Anaconda 3.6.5
Set up using [Normal Method](https://github.com/kanishka-linux/reminiscence#installation) on Debian Stretch
Running gunicorn behind Nginx as described in [README.md](https://github.com/kanishka-linux/reminiscence#gunicorn-plus-nginx-setup)

**Reproduction Steps**
1. Create a new folder with an alphanumeric name (e.g. `Recipes`)
1. Add URLs to the folder
1. From _Home_, rename the folder (_Select_ -> _Rename_)
1. Enter a name which contains a forward slash (`/`) or ampersand (`&`) (e.g. `Recipes & Cooking`)
1. Observe the rename succeeding, and the new name appearing properly on the _Home_ page
1. Attempt to open the folder to view the URLs inside

**Expected Behaviour**  
The folder should open as expected, and the special characters should be properly escaped in the page URL

**Observed Behaviour**  
The page fails to load (`HTTP 404`), as the special characters present in the URL are not escaped and are invalid (e.g. _Recipes & Cooking_ above tries loading as `https://myserver.example/myusername/Recipes & Cooking`)

**Recovery**  
I was able to repair my installation by editing the database manually and replacing all instances of the invalid folder name with a valid one in the `directory` column of the `page_library` table.

**Notes**  
It would be nice if these characters were allowed (and properly escaped so the page continues to load), but if this is infeasible then they should be disallowed in the folder name field to prevent breaking an installation. 

I'd be happy to dig in to the project and contribute a pull request if you'd like. Thanks for all your work on this project so far, it's awesome!

### PR DESCRIPTION
**Pull request by jonpavelich**
**Summary**  
This pull request implements directory URL slugs to allow special characters in directory names.

**Details**
 - A `directory_slug` field has been added to the Library model 
 - When directories are created or renamed, their "pretty" name is run through the built-in `slugify` function and stored alongside the directory name
 - The slugs are used for directory URLs while the pretty names are used wherever the user sees the directory names
 - To vastly reduce the complexity of the refactor, directory slugs are immediately translated back to directory names in each view function and directory names are still used throughout the code base (slugs are just for URLs)
 - The restriction on slashes (`/`) and colons (`:`) has been removed since it is no longer necessary

Closes #3

### CODE REVIEW

**Comment by jonpavelich** [comment]
I have tested **most** of the apps functionality with these changes, but more comprehensive testing should be done before this PR is merged (this was coded very late at night and it's pretty likely I missed something!)

I'll do more testing tomorrow and update the PR if I find anything.

**Comment by kanishka-linux** [comment]
I haven't tested it, but looks good. 
I'll test properly and review one more time this weekend, since it involved lot of changes.
In tests, if possible create a directory with special characters (i.e. /, :, ? $..etc) and test corresponding urlpattern, status code etc... Once this test is written, I think this feature will complete.

**Comment by kanishka-linux** [comment]
I looked into how **slugify** function works, and found that it is not bijective function. 
It means, it won't map directory entries uniquely.

Eg. It will map let's, let"s, let/s to lets. 

This is going to be problematic, since you are using **directory_slug** to find out **directory** name       using **_get_directory** function. So _get_directory function is going to return multiple rows. Selecting first row is not going fetch correct directory name every time, which will ultimately break the application.

Apart from above factor which is very crucial, **_get_directory** function is hitting the database every time in order to get directory name, which is unnecessary in many cases and will lead to some performance issues especially when getting archived resources.

Instead of slugify, we need some **one-to-one and onto** function which will map directory entries to a unique url pattern, which will also eliminate unnecessary database access when retrieving original directory name.

**Comment by kanishka-linux** [comment]
>I replaced the slugify function with URL encoding
This is working well
>The one downside I see to this approach is the URLs are kind of ugly
It is one of the reasons I've not used urlencoding. 
>A potential workaround is to use slugs and ids, so that slugs do not have to be unique
This is exactly what I was also thinking of. It is also long term solution and much better. But as you might have also seen that it will require a lot of changes.

One more potential solution (which is also easy) is to use django.urls.path and completely replace regex in urlpattern with '<username>/<str:directory>/'. Only characters which are not allowed in this pattern are /, ?, \, and #. It is just one line change. I think, for a time being it looks ok, before working on slug:id combo. What do you think?

**Comment by jonpavelich** [comment]
Hey, sorry for the silence, I'm currently out of the country and haven't been on top of GitHub. I can't update my pull request until I'm back, so this is kind of on hold for now. Once I'm back I'd be happy to look at just tackling the slug:id combo, I think it might be better to just spend some extra time to fix it right. If you want to get a fix in sooner for this, I agree with making the `<username>/<str:directory>/` change (and this PR can just be closed).

**Comment by kanishka-linux** [comment]
> Once I'm back I'd be happy to look at just tackling the slug:id combo

That will be great. Take your time. I've added some error checking, and it is now possible to rename/remove every directory with invalid name.

Apart from **/id/slug** pattern, you can also take a look at **id-slug** pattern. Here we don't have to change urlpattern, and we can extract id from it. Only problem is that id is separate for every url, which may create few problems, like unnecessary one more database access for getting directory name.

**Pull request closed without merging**
