### PR TITLE
fixes: postgress container doesn't start up but throws error #39

### PR DESCRIPTION
**Pull request by s3h10r**

### CODE REVIEW

**Comment by kanishka-linux** [comment]
After reading the postgres issue link that you posted previously, I also think that we should use some random username/password instead of allowing access without any restriction. What do you think? Have you tried setting up username/password for postgres in docker-compose file?

**Comment by s3h10r** [comment]
Mmh. I think you're right. Headed for the most lazy solution working... ;) yes, giving access to the db from anywhere without any password is insecure and may be really dangerous if someone starts up the `docker-compose` environment without being aware of this. Didn't tried to put the usr/pwd into the docker-compose file itself so far - should work imho. But having 2 locations for a password setting is inconvinient imho. Maybe we can use an ENV-variable instead? What do you think?

**Comment by s3h10r** [comment]
btw. tried setting up the username/password for postgres in docker-compose file now...

**Comment by s3h10r** [comment]
btw. update: tried it as suggested with giving username/password based on the `reminiscence/dockersettings.py` now: unfortunatly without luck. :-/ so i think this patch wouldn't harm. it seems not not possible do do a `docker-compose up` on a fresh installation without it imho - no matter if windows/macos/lixux/raspi at the moment (means the set password in `reminiscence/dockersettings.py`is ignored in the old setup too, so nothing's lost).

**Comment by kanishka-linux** [comment]
That's strange. I think setting up something like below in docker-compose.yml db section should work
```environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=password```
I think we'll need to explore more about it then. I'll try to look at it, and in between if you come across any solution then keep posted.

**Comment by s3h10r** [comment]
Naaaah. I did:

```
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="password"
      - POSTGRES_DB="postgres"
```

which fails. 

Now i tried:

```
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
```

which works. :D 

At least on macos, so i think i just got the syntax wrong. #) Will try this on the RPi too this week.

**Comment by s3h10r** [comment]
btw. created a better patch which uses usr/pwd settings via adding a`docker.env`-file which is used then in `reminiscence/dockersettings.py` (falls back to defaults if not present) and `docker-compose.yml`:

https://github.com/s3h10r/reminiscence/commit/6f1568bb292e8c651bbf231e11ac22d3bb45eaa8

this works fine on fresh setups (tested this on a macos x).  

but i guess in setups with already a db present we either need to use the setting `POSTGRES_HOST_AUTH_METHOD=trust` like in this patch or the user has to create a suiting postgres-user with suiting password and access right for the db (means in the old setup no user for the db was created or? not sure...) after running with the "new behaviour of postgres:latest"

aynways: i would prefer the new patch. what do you think? should i send another pull-request (and close this one)?

**Comment by kanishka-linux** [comment]
Yes, I also think that new patch is better.  Reading username/password directly from env vars is much more preferable.
 
We can also add one comment in the `docker-compose.yml` about using `POSTGRES_HOST_AUTH_METHOD=trust` - in case someone wants to try this due to some issue.

I think you can make changes in this PR itself. Make changes, add files and just amend previous commit instead of new commit and then force push to this branch.

**Comment by kanishka-linux** [comment]
Great! Merging changes.

**Pull request merged**
