### PR TITLE
logo added

### PR DESCRIPTION
**Pull request by reallinfo**

### CODE REVIEW

**Comment by kanishka-linux** [comment]
Great! I'll try them out in one or two days.

**Comment by reallinfo** [comment]
Oh okay. You can write me if you need anything. Also, If you want, I can design a logo for other projects. Feel free to say. Good works.

**Comment by kanishka-linux** [comment]
I tried few logos and finalized two.

1.  svg/horizontal_white.svg (It looks good on the black panel)

2. svg/horizontal_blue.svg (It will be on the login page)

There are just few minor issues. 

* These images are pretty big, and when we make them smaller to fit into particular position, they do not render properly. On the black panel, I'm using image height of 24px and on the login page I'm trying 32px.

* letters of horizontal_blue.svg are pretty thick. Can you make it similar to that of on the github login page?

Apart from above two logos, I'm also interested in horizontal_blue.svg without letters, which also I want to try it on the login page. If you can create it, then it will be great!

> I can design a logo for other projects.

If you are interested then there is another project of mine [kawaii-player](https://github.com/kanishka-linux/kawaii-player), which is in need of good icon/logo. There is also [one issue](https://github.com/kanishka-linux/kawaii-player/issues/7) about it which has been pending since last year. If you want, then you can contribute to it afterwards.

**Comment by reallinfo** [comment]
I think you want these variations. Is it correct? 

rr

Also, i made the letters thinner. I think that looks better. Btw, From the login page, do you mean readme file? like this?

rr2

**Pull request closed without merging**
